services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173' # Mapeando a porta do contêiner para a porta do host
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
